# SPDX-FileCopyrightText: 2025 Pavel Dimov <@sagat79>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Validate Ghost configuration
  tags:
    - setup-all
    - setup-ghost
    - install-all
    - install-ghost
  block:
    - name: Check if Ghost hostname is set
      ansible.builtin.fail:
        msg: "ghost_hostname must be set to a valid hostname"
      when: ghost_hostname | length == 0

    - name: Check if Ghost UID is set
      ansible.builtin.fail:
        msg: "ghost_uid must be set to a valid user ID"
      when: ghost_uid | length == 0

    - name: Check if Ghost GID is set
      ansible.builtin.fail:
        msg: "ghost_gid must be set to a valid group ID"
      when: ghost_gid | length == 0

    - name: Check if Ghost database hostname is set
      ansible.builtin.fail:
        msg: "ghost_database_hostname must be set to a valid hostname"
      when: ghost_database_hostname | length == 0

    - name: Check if Ghost database password is set
      ansible.builtin.fail:
        msg: "ghost_database_password must be set to a valid password"
      when: ghost_database_password | length == 0

    - name: Validate database type
      ansible.builtin.fail:
        msg: "ghost_database_type must be either 'mysql' or 'postgres'"
      when: ghost_database_type not in ['mysql', 'postgres']

    - name: Validate mail configuration when enabled
      when: ghost_mail_enabled | bool
      block:
        - name: Check if mail host is set
          ansible.builtin.fail:
            msg: "ghost_mail_options_host must be set when ghost_mail_enabled is true"
          when: ghost_mail_options_host | length == 0

        - name: Check if mail username is set
          ansible.builtin.fail:
            msg: "ghost_mail_options_auth_user must be set when ghost_mail_enabled is true"
          when: ghost_mail_options_auth_user | length == 0

        - name: Check if mail password is set
          ansible.builtin.fail:
            msg: "ghost_mail_options_auth_pass must be set when ghost_mail_enabled is true"
          when: ghost_mail_options_auth_pass | length == 0

        - name: Check if mail from email is set
          ansible.builtin.fail:
            msg: "ghost_mail_from must be set when ghost_mail_enabled is true"
          when: ghost_mail_from | length == 0
