# SPDX-FileCopyrightText: 2025 Pavel Dimov <@sagat79>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Auto-merge Renovate PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    name: Auto-merge Renovate PRs
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]' || github.actor == 'app/renovate'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Enable auto-merge for Renovate PRs
        run: |
          # Check if PR is from Renovate and has automerge enabled in config
          if [[ "${{ github.event.pull_request.user.login }}" == "renovate[bot]" || "${{ github.event.pull_request.user.login }}" == "app/renovate" ]]; then
            echo "Enabling auto-merge for Renovate PR #${{ github.event.pull_request.number }}"
            
            # Enable auto-merge with squash strategy
            gh pr merge ${{ github.event.pull_request.number }} --squash --auto
            
            echo "Auto-merge enabled successfully"
          else
            echo "PR is not from Renovate, skipping auto-merge"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
